ALTER TABLE "Recipe"
ADD COLUMN IF NOT EXISTS "semanticText" TEXT,
ADD COLUMN IF NOT EXISTS "embeddingModel" TEXT,
ADD COLUMN IF NOT EXISTS "embeddingVector" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN IF NOT EXISTS "embeddingUpdatedAt" TIMESTAMP(3);
